{% set name = "toml" %}
{% set version = "0.9.5" %}
{% set sha256 = "c79b2dc8cc8f2e841dd1ed3786db7a7b8b40c17ea2daf182ad7017554a4d544a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256|lower }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python

test:
  imports:
    - toml
  commands:
    - conda inspect linkages -p $PREFIX toml  # [not win]
    - conda inspect objects -p $PREFIX toml   # [osx]

about:
  home: https://github.com/uiri/toml
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python lib for TOML.'

extra:
  recipe-maintainers:
    - rlaverde
    - holgern
